Iter5
ipcross/urlShortener pull request #5
Opened 2024-12-01 11:20 UTC by ipcross

2024-12-04 09:24 UTC, s-shpak requested changes

2024-12-04 09:24 UTC, s-shpak commented on .github/workflows/golangci-lint.yml
> +#name: golangci-lint
Почему ты отключил линтер ? Проверка не проходит ?

2024-12-04 09:24 UTC, s-shpak commented on cmd/client/main.go
Этот файл не нужен, его можно удалить. Все проверки лучше делать при помощи тестов

2024-12-04 09:24 UTC, s-shpak commented on cmd/shortener/main.go
Постарайся оставлять в `main.go` (и в пакете `main`) как можно меньше логики: там могут лежать только создание и настройка компонентов и запуск сервиса. Всю остальную логику нужно перенести в `internal`.

2024-12-04 09:24 UTC, s-shpak commented on cmd/shortener/main.go
> +		log.Println(err)
В ошибки лучше добавлять контекст: например, текст, объясняющий, что именно пошло не так и где

2024-12-04 09:24 UTC, s-shpak commented on cmd/shortener/main.go
> +		log.Println(err)
После этой ошибки нельзя продолжать обработку запроса

2024-12-04 09:24 UTC, s-shpak commented on config/config.go
> +var ServerSettings settings
Не используй глобальные переменные. Ты можешь создавать объект, наполнять его и передавать туда, где он будет использоваться

2024-12-04 09:24 UTC, s-shpak commented on config/config.go
> +	if envAddressRun := os.Getenv("SERVER_ADDRESS"); envAddressRun != "" {
Вместо `Getenv` лучше использовать `LookupEnv` (https://pkg.go.dev/os#LookupEnv) для того чтобы отличать пустую переменную окружения от необъявленной

2024-12-05 14:28 UTC, ipcross commented on .github/workflows/golangci-lint.yml
> +#name: golangci-lint
Да, миллион не понятных ошибок.

2024-12-05 14:28 UTC, ipcross commented on cmd/client/main.go
Удалил файл.

2024-12-05 15:57 UTC, ipcross commented on cmd/shortener/main.go
> +		log.Println(err)
Добавил return

2024-12-05 15:57 UTC, ipcross commented on config/config.go
> +var ServerSettings settings
Убрал

2024-12-05 15:57 UTC, ipcross commented on config/config.go
> +	if envAddressRun := os.Getenv("SERVER_ADDRESS"); envAddressRun != "" {
Поменял

2024-12-05 15:57 UTC, ipcross commented on cmd/shortener/main.go
Перенес в app

2024-12-05 15:58 UTC, ipcross commented on cmd/shortener/main.go
> +		log.Println(err)
Добавил контекст

2024-12-06 14:27 UTC, s-shpak commented on .github/workflows/golangci-lint.yml
> +#name: golangci-lint
Нет, линтер должен быть подключен. Разберись, пожалуйста, с ошибками. Если какие-то непонятны -- пиши в пачку

2024-12-06 14:30 UTC, s-shpak requested changes

2024-12-06 14:30 UTC, s-shpak commented on internal/app/app.go
> +var mapper Mapper
Не используй глобальные переменные

2024-12-06 14:30 UTC, s-shpak commented on internal/app/app.go
> +	log.Fatal(http.ListenAndServe(settings.AddressRun, myRouter()))
Фаталиться лучше из точки входа: т.е. ошибку можно пробросить до `main`

2024-12-06 14:30 UTC, s-shpak commented on internal/app/app.go
> +		log.Printf("PostHandler err: %v", err)
Какой ответ необходимо вернуть пользователю здесь ?

2024-12-06 14:30 UTC, s-shpak commented on internal/app/app.go
> +	Counter int
Зачема нужна эта переменная ?

2024-12-06 14:30 UTC, s-shpak commented on internal/app/app.go
> +	URL     map[int]string
Это поле не должно быть экспортируемым

2024-12-09 07:22 UTC, ipcross commented on .github/workflows/golangci-lint.yml
> +#name: golangci-lint
Подключил, осталось 4 ошибки общие, которые были в коде из вебинара и теории курса.

2024-12-09 07:22 UTC, ipcross commented on internal/app/app.go
> +var mapper Mapper
Убрал

2024-12-09 07:23 UTC, ipcross commented on internal/app/app.go
> +	log.Fatal(http.ListenAndServe(settings.AddressRun, myRouter()))
перенес

2024-12-09 07:23 UTC, ipcross commented on internal/app/app.go
> +		log.Printf("PostHandler err: %v", err)
Добавил 400

2024-12-09 07:23 UTC, ipcross commented on internal/app/app.go
> +	Counter int
Переделал на 6 рандомных символов

2024-12-09 07:23 UTC, ipcross commented on internal/app/app.go
> +	URL     map[int]string
Удалил

2024-12-09 09:51 UTC, s-shpak commented on .github/workflows/golangci-lint.yml
> +#name: golangci-lint
Привет! Код в теории не всегда написан идеально. Попробуй понять, о чем эти ошибки (они полезные), и поправь их. Если будет неясно -- напиши в пачку

2024-12-09 09:54 UTC, s-shpak requested changes

2024-12-09 09:54 UTC, s-shpak commented on internal/service/service.go
> +	f.store.SetMapper(&repository.SetMapperRequest{
Что если проверка завершилась успешно, но до того, как ты добавил новую коротку ссылку в хранилище, другая горутина добавит ее же (случайно сгенерирует такое же значение)? Подумай, как это исправить

2024-12-10 14:05 UTC, ipcross commented on .github/workflows/golangci-lint.yml
> +#name: golangci-lint
Поправил

2024-12-10 14:05 UTC, ipcross commented on internal/service/service.go
> +	f.store.SetMapper(&repository.SetMapperRequest{
Тут не знаю.

2024-12-10 20:19 UTC, s-shpak commented on internal/service/service.go
> +	f.store.SetMapper(&repository.SetMapperRequest{
Надо чтобы при добавлении уже существующего значения, хранилище само проверяло, есть ли оно, и если да, то возвращало ошибку. Тогда ты сможешь зашитить проверку и добавление мьютексом и избежишь коллизии

2024-12-10 20:20 UTC, s-shpak requested changes
См. комментарий

2024-12-11 16:14 UTC, ipcross commented on internal/service/service.go
> +	f.store.SetMapper(&repository.SetMapperRequest{
Добавил.

2024-12-12 19:12 UTC, s-shpak approved these changes

2024-12-13 06:40 UTC, merged