Iter9
ipcross/urlShortener pull request #9
Opened 2024-12-17 15:00 UTC by ipcross

2024-12-17 21:40 UTC, s-shpak requested changes

2024-12-17 21:40 UTC, s-shpak commented on cmd/shortener/main_test.go
> +		body, _ := json.Marshal(postBody)
Ошибки необходимо проверять и в тестах

2024-12-17 21:40 UTC, s-shpak commented on internal/adapters/filestorage/filestorage.go
> +	return fmt.Errorf("wrap: %w", err)
Это всегда будет возвращать ошибку, кажется, что это неправильно

2024-12-17 21:40 UTC, s-shpak commented on internal/handlers/handlers.go
> +		res.WriteHeader(http.StatusInternalServerError)
Здесь ошибку необходимо логировать

2024-12-17 21:40 UTC, s-shpak commented on internal/handlers/handlers.go
> +		log.Printf("failed to save URL: %v", err)
А здесь либо нет, если это `Bad Request`, либо необходимо вернуть `Internal Server Error`

2024-12-17 21:40 UTC, s-shpak commented on internal/handlers/handlers.go
> +		return
Что сделать с этой ошибкой ?

2024-12-17 21:40 UTC, s-shpak commented on internal/logger/logger.go
> +		log.Fatal(err)
Не надо фаталиться из глубины кода, прокидывай ошибку наверх. Фаталиться лучше только из `main()`

2024-12-17 21:40 UTC, s-shpak commented on internal/middleware/gzip.go
> +		log.Fatal(err)
См. комментарий выше

2024-12-17 21:40 UTC, s-shpak commented on internal/repository/repository.go
> +func NewStore(cfg config.ServerSettings) *Store {
В этом спринте мы добавляем обособленную часть функционала к хранилищу: запись в файл. То есть новый тип хранилища полностью повторяет функционал MemoryStore и расширяет его. Но мы оставляем возможность запустить сервис без записи в файл. Потому кажется логичным не изменять существующую структуру, и не дуплицировать функционал, а написать обертку над MemoryStore.

Для этого можно использовать композицию и встроить MemoryStore в новую структуру FileStore. При вызове сохранения, например, новая структура будет вызывать вначале добавление новой записи в память (через встроенный объект), а потом сохранение в файл.

В этом случае убедись, что ты выполняешь инициализацию нужного типа при старте сервиса (можно использовать паттерн Factory, как разбирали на первом вебинаре).

2025-01-09 12:27 UTC, ipcross commented on cmd/shortener/main_test.go
> +		body, _ := json.Marshal(postBody)
Добавил

2025-01-09 12:27 UTC, ipcross commented on internal/adapters/filestorage/filestorage.go
> +	return fmt.Errorf("wrap: %w", err)
Поправил

2025-01-09 12:27 UTC, ipcross commented on internal/handlers/handlers.go
> +		res.WriteHeader(http.StatusInternalServerError)
Добавил

2025-01-09 12:27 UTC, ipcross commented on internal/handlers/handlers.go
> +		log.Printf("failed to save URL: %v", err)
Поменял

2025-01-09 12:27 UTC, ipcross commented on internal/handlers/handlers.go
> +		return
Логировать

2025-01-09 12:27 UTC, ipcross commented on internal/logger/logger.go
> +		log.Fatal(err)
Убрал

2025-01-09 12:28 UTC, ipcross commented on internal/middleware/gzip.go
> +		log.Fatal(err)
Убрал

2025-01-09 12:29 UTC, ipcross commented on internal/repository/repository.go
> +func NewStore(cfg config.ServerSettings) *Store {
Предложенное решение посчитал излишним усложнением, потому что текущая реализация позволяет работать без сохранения в файла.

2025-01-11 21:24 UTC, s-shpak approved these changes

2025-01-11 22:04 UTC, merged